---

- hosts: all
  become: true
  tasks:


  - name: install apache and php
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php
    pacman:
      name:
        - apache              
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"

