---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Arch)
    tags: always
    pacman:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: apache,apache2,ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php
    tags: apache,archlinux,
    pacman:
      name:
        - apache              
        - php 
      state: latest
    when: ansible_distribution == "Archlinux"

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644	

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (Arch)
    tags: db,mariadb,archlinux
    apt:
      name: mariadb
      state: latest
    when: ansible_distribution == "Archlinux"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
